name = "encrypt"
pages_build_output_dir = "./dist"

[vars]
MY_NAME = "Hono"

[[kv_namespaces]]
binding = "dataTest"
id = "04d11a7d801342f0835434ea0a16efdb"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"